
option(BUILD_TESTS "Build tests" ON)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

set(L-LANG_VERSION_MAJOR 0)
set(L-LANG_VERSION_MINOR 1)
set(L-LANG_VERSION_PATCH 0)
set(L-LANG_VERSION "${L-LANG_VERSION_MAJOR}.${L-LANG_VERSION_MINOR}.${L-LANG_VERSION_PATCH}")

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(L_COMPILER_NAME "L-lang")
set(L_STDLIB_NAME "L-Langlib")

set(CMAKE_CXX_FLAGS "-Wall -Wextra -Wpedantic -Werror")
set(CMAKE_CXX_COMPILER "/usr/bin/c++")

set(CMAKE_BUILD_TYPE Debug)

# L-Lang Compiler

option(L-LANG_BUILD_COMPILER "Build L-Lang compiler" ON)

set(L-LANG_COMPILER_DIR ${CMAKE_SOURCE_DIR}/LumC)

set(L-LANG_COMPILER_MAIN ${L-LANG_COMPILER_DIR}/app/main.cc)

set(L-LANG_COMPILER_SOURCES)
